'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const HOST=process.env.HOST||'0.0.0.0';
const PORT=Number(process.env.PORT||8787);
const ROOT=path.join(os.homedir(),'.autonomous-html-server');
const STATE=path.join(ROOT,'state.json');
const BACKUP=path.join(ROOT,'state.backup.json');
const LOG=path.join(ROOT,'server.log');
const HTML=path.join(__dirname,'Server_REAL.html');
fs.mkdirSync(ROOT,{recursive:true});
let runtime={startedAt:Date.now(),requests:0,errors:0,jobsFinished:0,recoveries:0,queueBusy:false,state:{version:2,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),kv:{},jobs:[],nextJobId:1,snapshots:[]}};
function log(level,...v){const line=`[${new Date().toISOString()}] [${level}] ${v.map(x=>typeof x==='string'?x:JSON.stringify(x)).join(' ')}\n`;process.stdout.write(line);try{fs.appendFileSync(LOG,line)}catch{}}
function atomic(file,obj){const tmp=file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(obj,null,2),'utf8');fs.renameSync(tmp,file)}
function save(){runtime.state.updatedAt=new Date().toISOString();try{if(fs.existsSync(STATE))fs.copyFileSync(STATE,BACKUP);atomic(STATE,runtime.state);return true}catch(e){runtime.errors++;log('ERROR',e.stack||e);return false}}
function load(){for(const f of [STATE,BACKUP]){try{if(fs.existsSync(f)){runtime.state={...runtime.state,...JSON.parse(fs.readFileSync(f,'utf8'))};if(f===BACKUP)runtime.recoveries++;return}}catch(e){log('WARN',f,e.message)}}}
function recoverJobs(){const now=Date.now();for(const j of runtime.state.jobs){if(j.status==='processing'&&now-(j.startedAt||j.createdAt||now)>10000){j.status='pending';j.recoveredAt=now;runtime.recoveries++}}}
function common(){return {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Cache-Control':'no-store'}}
function json(res,status,obj){const b=JSON.stringify(obj);res.writeHead(status,{...common(),'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(b)});res.end(b)}
async function body(req){return new Promise((resolve,reject)=>{const chunks=[];let n=0;req.on('data',c=>{n+=c.length;if(n>10*1024*1024){reject(new Error('payload demasiado grande'));req.destroy();return}chunks.push(c)});req.on('end',()=>resolve(Buffer.concat(chunks).toString('utf8')));req.on('error',reject)})}
async function execute(job){await new Promise(r=>setTimeout(r,250));return {input:job.payload,processedAt:Date.now(),checksum:crypto.createHash('sha256').update(JSON.stringify(job.payload)).digest('hex')}}
async function queueTick(){if(runtime.queueBusy)return;const j=runtime.state.jobs.find(x=>x.status==='pending');if(!j)return;runtime.queueBusy=true;j.status='processing';j.startedAt=Date.now();j.attempts=(j.attempts||0)+1;save();try{j.result=await execute(j);j.status='completed';j.completedAt=Date.now();runtime.jobsFinished++;log('JOB',j.id,'completed')}catch(e){runtime.errors++;j.status='pending';j.lastError=String(e.stack||e);log('JOB_ERROR',j.id,j.lastError)}finally{runtime.queueBusy=false;save()}}
load();recoverJobs();save();
setInterval(queueTick,250);
setInterval(()=>{recoverJobs();save()},3000);
setInterval(save,30000);
const server=http.createServer(async(req,res)=>{runtime.requests++;if(req.method==='OPTIONS'){res.writeHead(204,common());return res.end()}try{const u=new URL(req.url,'http://localhost');if(req.method==='GET'&&(u.pathname==='/'||u.pathname==='/index.html')){const b=fs.readFileSync(HTML);res.writeHead(200,{...common(),'Content-Type':'text/html; charset=utf-8','Content-Length':b.length});return res.end(b)}if(req.method==='GET'&&u.pathname==='/api/health')return json(res,200,{ok:true,nodeVersion:process.version,pid:process.pid,address:`http://127.0.0.1:${PORT}`,uptimeMs:Date.now()-runtime.startedAt,requests:runtime.requests,errors:runtime.errors,jobsFinished:runtime.jobsFinished,recoveries:runtime.recoveries,queuedJobs:runtime.state.jobs.filter(j=>j.status==='pending').length,runningJobs:runtime.state.jobs.filter(j=>j.status==='processing').length});if(req.method==='GET'&&u.pathname==='/api/jobs')return json(res,200,runtime.state.jobs);if(req.method==='POST'&&u.pathname==='/api/jobs'){const raw=await body(req);const payload=raw?JSON.parse(raw):{};const j={id:runtime.state.nextJobId++,status:'pending',attempts:0,payload,createdAt:Date.now()};runtime.state.jobs.push(j);save();return json(res,201,j)}if(req.method==='POST'&&u.pathname==='/api/snapshot'){const snap={id:crypto.randomUUID(),time:Date.now(),state:JSON.parse(JSON.stringify(runtime.state))};runtime.state.snapshots.push({id:snap.id,time:snap.time});if(runtime.state.snapshots.length>100)runtime.state.snapshots=runtime.state.snapshots.slice(-100);atomic(path.join(ROOT,`${snap.time}-${snap.id}.snapshot.json`),snap);save();return json(res,201,{ok:true,id:snap.id})}if(req.method==='POST'&&u.pathname==='/api/state/save'){const ok=save();return json(res,ok?200:500,{ok})}if(u.pathname.startsWith('/api/kv/')){const k=decodeURIComponent(u.pathname.slice('/api/kv/'.length));if(req.method==='GET'){if(!Object.prototype.hasOwnProperty.call(runtime.state.kv,k))return json(res,404,{error:'NOT_FOUND'});return json(res,200,{key:k,value:runtime.state.kv[k]})}if(req.method==='PUT'){const raw=await body(req);runtime.state.kv[k]=raw?JSON.parse(raw):null;save();return json(res,200,{ok:true,key:k,value:runtime.state.kv[k]})}if(req.method==='DELETE'){delete runtime.state.kv[k];save();return json(res,200,{ok:true})}}return json(res,404,{error:'ROUTE_NOT_FOUND'})}catch(e){runtime.errors++;log('HTTP_ERROR',e.stack||e);return json(res,500,{error:'INTERNAL_ERROR',message:e.message})}});
server.on('clientError',(err,socket)=>{runtime.errors++;log('CLIENT_ERROR',err.message);if(socket.writable)socket.end('HTTP/1.1 400 Bad Request\r\n\r\n')});
server.listen(PORT,HOST,()=>log('SERVER',`HTTP escuchando en ${HOST}:${PORT}`));
for(const sig of ['SIGINT','SIGTERM'])process.on(sig,()=>{save();server.close(()=>process.exit(0));setTimeout(()=>process.exit(1),3000).unref()});
